CONFIG = {"actions_list": ["no_change", "speed_up", "slow_down"],
          "state_features": ["position", "velocity", "road_grade"],
          "reward": 0,
          "fixed_rewards_dict": {"reached_goal": 80,
                           "per_step_cost": -3,   
                           },
          "min_velocity": 0,
          "max_velocity": 6,
          "min_position": 0,
          "max_position": 40,
          "init_state_pos": 0,
          "goal_state_pos": 40,
          "init_state_vel": 2,
          "init_road_grade": 0,
          "max_road_grade": 2,
          "min_road_grade": 0,
          }
